admin-ch/CovidCertificate-App-Config-Service

- .github/workflows/maven.yml
- .github/workflows/tagged_release.yaml
This pull-request removes an unused Github action. It also pins a specific commit of the third-party action to reduce risk of supply chain attacks.
> Improve GitHub actions

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
This PR sets the forceUpdate flag for app version 1.0.0. (due to update in the verification logic this apps need to be updated)
> Force update v1.0.0

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/BaseControllerTest.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/BaseControllerTest.java
Force update all apps below 1.2.0.
> Force Update below 1.2.0

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/FaqHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/ConfigResponse.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/test/java/ch/admin/bag/covidcertificate/backend/config/shared/ConfigAsserter.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/BaseControllerTest.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/BaseControllerTest.java
This PR adds two new fields for the Android Wallet App configuration
> New android configs.

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
Disable forceupdate for android till new version is available
> Disable forceupdate for android till new version is available

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/FaqHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/BaseControllerTest.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/WalletWsBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockFaqLinkConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockForceUpdateConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockInfoBoxConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/model/WalletConfigResponse.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/BaseControllerTest.java
this pull request adds new faqs and feature flags for light certificate and pdf generation
> Feature: new faqs and flags for certificate light / pdf

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
Reverts admin-ch/CovidCertificate-App-Config-Service#13
> Revert "Re-enable force-update for Android apps < 1.2.0"

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/config/WSBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/InfoBoxHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/test/java/ch/admin/bag/covidcertificate/backend/config/shared/ConfigAsserter.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/WalletWsBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockFaqLinkConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockForceUpdateConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockInfoBoxConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/BaseControllerTest.java
this pull request adds an update info box to the config response for android wallet apps below version 2.0
> add update info box for android <2.0

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/ConfigResponse.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
true for wallet, false for verifier
> add flag for timeshift detection

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/BaseControllerTest.java
Force update for everyone <1.2.0 on both
Show infobox <2.7.0 on wallet﻿
> force update for all below 1.2.0 and wallet infobox below 2.7.0

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/VaccinationHintHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/VaccinationBookingInfo.java
this pr adds vaccination impf check infos to be displayed in the app
> add vaccination impf check infos

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
this pull request updates the youtube video urls in the FAQ
> update youtube url

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/config/ActuatorSecurity.java
- ch-covidcertificate-backend-config/pom.xml
- Spring Boot 2.6.1
- upgrade Spring cloud as needed, fix annotation typo
> Upgrade to latest Spring Boot 2.x.

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
this pull request removes an accidental new line from a poeditor text
> remove accidental new line

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/config/WSBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/CheckModeInfoHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/RefreshButtonInfoHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/CheckMode.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/Icon.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/RefreshButtonInfo.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/WalletConfigResponse.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/application-local.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/WalletWsBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockFaqLinkConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockForceUpdateConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockInfoBoxConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/BaseControllerTest.java
this pull request adds a feature flag to disable the refresh button in the wallet app
> add feature flag to disable refresh button

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
this pull request fixes a french translation of an info string
> fix french translation

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/model/WalletConfigResponse.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/application-local.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/WalletWsBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockFaqLinkConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockForceUpdateConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockInfoBoxConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
Requires config option `ws.wallet.ratConversion.enabled`
> add feature flag and URL for RAT recovery conversion form

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
> Fix URL for immunityrequest

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/application-local.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/WalletWsBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockFaqLinkConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockForceUpdateConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/config/mock/MockInfoBoxConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-wallet-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/wallet/ws/controller/WalletConfigController.java
> make RAT conversion form URL a cofig parameter

- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/java/ch/admin/bag/covidcertificate/backend/config/shared/helper/InfoBoxHelper.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_de.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_en.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_fr.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_it.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-shared/src/main/resources/i18n/messages_rm.properties
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/config/VerifierWsBaseConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/config/mock/MockFaqLinkConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/config/mock/MockForceUpdateConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/config/mock/MockInfoBoxConfig.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/main/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/controller/VerifierConfigController.java
- ch-covidcertificate-backend-config/ch-covidcertificate-backend-config-verifier-ws/src/test/java/ch/admin/bag/covidcertificate/backend/config/verifier/ws/BaseControllerTest.java
Both apps should show an infobox to inform users about the upcoming system shutdown
> Infobox about system shutdown
